//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcijalni_2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Proizvodi
    {
        [Required]
        public int id { get; set; }

        [Required]
        [StringLength (15, ErrorMessage ="Obavezan Unos! - max duljina 15 znakova")]
        public string naziv { get; set; }

        [Required (ErrorMessage ="Obavezan Unos!")]       
        public decimal cijena { get; set; }
        public Nullable<bool> kupljen { get; set; }
    }
}
